/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author laboratorio
 */
public class ModuloCitas extends javax.swing.JFrame {

    JFileChooser Archivo = new JFileChooser();
    
    /**
     * Creates new form ModuloAutomovil
     */
    public ModuloCitas() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Módulo Camiones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblCitaAgregarVehiculoPlaca = new javax.swing.JLabel();
        lblCitaAgregarLugar = new javax.swing.JLabel();
        lblCitaAgregarCosto = new javax.swing.JLabel();
        txtCitaAgregarVehiculoPlaca = new javax.swing.JTextField();
        btnCitaAgregar = new javax.swing.JButton();
        txtCitaAgregarCosto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbCitaAgregarLugar = new javax.swing.JComboBox();
        btnAbrirCitas = new javax.swing.JButton();
        btnGuardarCitas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblAutobusModificarPlaca = new javax.swing.JLabel();
        txtCitaModificarIdCita = new javax.swing.JTextField();
        btnCitaModificar = new javax.swing.JButton();
        lblAutobusModificarPlaca1 = new javax.swing.JLabel();
        cmbCitaModificarLugar = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        lblCitaBuscarIdCita = new javax.swing.JLabel();
        txtCitaBuscarIdCita = new javax.swing.JTextField();
        btnCitaBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taCitaBuscar = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        lblCitaEliminarIdCita = new javax.swing.JLabel();
        txtCitaEliminarIdCita = new javax.swing.JTextField();
        btnCitaEliminar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnCitaMostrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taCitaMostrar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblCitaAgregarVehiculoPlaca.setText("Vehículo:");

        lblCitaAgregarLugar.setText("Lugar:");

        lblCitaAgregarCosto.setText("Costo:");

        btnCitaAgregar.setText("Agregar");
        btnCitaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("(Placa)");

        cmbCitaAgregarLugar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "San José", "Alajuela", "Heredia", "Cartago", "Puntarenas", "Guanacaste", "Limón" }));

        btnAbrirCitas.setText("Abrir");
        btnAbrirCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirCitasActionPerformed(evt);
            }
        });

        btnGuardarCitas.setText("Guardar");
        btnGuardarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCitaAgregarVehiculoPlaca)
                            .addComponent(lblCitaAgregarLugar)
                            .addComponent(lblCitaAgregarCosto))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtCitaAgregarCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbCitaAgregarLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCitaAgregarVehiculoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(btnAbrirCitas))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnGuardarCitas))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCitaAgregar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCitaAgregarVehiculoPlaca)
                    .addComponent(txtCitaAgregarVehiculoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnAbrirCitas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCitaAgregarLugar)
                    .addComponent(cmbCitaAgregarLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarCitas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCitaAgregarCosto)
                    .addComponent(txtCitaAgregarCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCitaAgregar)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel2);

        lblAutobusModificarPlaca.setText("IdCita:");

        btnCitaModificar.setText("Modificar");
        btnCitaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaModificarActionPerformed(evt);
            }
        });

        lblAutobusModificarPlaca1.setText("Nuevo Lugar:");

        cmbCitaModificarLugar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "San José", "Alajuela", "Heredia", "Cartago", "Puntarenas", "Guanacaste", "Limón" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCitaModificar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutobusModificarPlaca)
                            .addComponent(lblAutobusModificarPlaca1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCitaModificarIdCita, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCitaModificarLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutobusModificarPlaca)
                    .addComponent(txtCitaModificarIdCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAutobusModificarPlaca1)
                    .addComponent(cmbCitaModificarLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnCitaModificar)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar", jPanel3);

        lblCitaBuscarIdCita.setText("IdCita:");

        btnCitaBuscar.setText("Buscar");
        btnCitaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaBuscarActionPerformed(evt);
            }
        });

        taCitaBuscar.setEditable(false);
        taCitaBuscar.setColumns(20);
        taCitaBuscar.setRows(5);
        jScrollPane1.setViewportView(taCitaBuscar);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblCitaBuscarIdCita)
                        .addGap(27, 27, 27)
                        .addComponent(txtCitaBuscarIdCita, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCitaBuscar))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCitaBuscarIdCita)
                    .addComponent(txtCitaBuscarIdCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCitaBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscar", jPanel4);

        lblCitaEliminarIdCita.setText("IdCita:");

        btnCitaEliminar.setText("Eliminar");
        btnCitaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblCitaEliminarIdCita)
                        .addGap(27, 27, 27)
                        .addComponent(txtCitaEliminarIdCita, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCitaEliminar))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCitaEliminarIdCita)
                    .addComponent(txtCitaEliminarIdCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCitaEliminar)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel6);

        btnCitaMostrar.setText("Mostrar");
        btnCitaMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaMostrarActionPerformed(evt);
            }
        });

        taCitaMostrar.setEditable(false);
        taCitaMostrar.setColumns(20);
        taCitaMostrar.setRows(5);
        jScrollPane2.setViewportView(taCitaMostrar);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnCitaMostrar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCitaMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mostrar", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCitaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitaAgregarActionPerformed
        // TODO add your handling code here:
        int vPlaca = Integer.parseInt(txtCitaAgregarVehiculoPlaca.getText());
        
        String vVehiculo = PantallaPrincipal.Gestora.BuscarVehiculoPorPlaca(vPlaca);
        
        int IndexLugar = cmbCitaAgregarLugar.getSelectedIndex();
        String vLugar = (String)cmbCitaAgregarLugar.getItemAt(IndexLugar);
        
        int vCosto =  Integer.parseInt(txtCitaAgregarCosto.getText());
        
        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.AgregarCita(vVehiculo, vLugar, vCosto));

    }//GEN-LAST:event_btnCitaAgregarActionPerformed

    private void btnCitaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitaBuscarActionPerformed
        // TODO add your handling code here:
        int vIdCita = Integer.parseInt(txtCitaBuscarIdCita.getText());
        
        taCitaBuscar.setText(PantallaPrincipal.Gestora.BuscarCitas(vIdCita));
    }//GEN-LAST:event_btnCitaBuscarActionPerformed

    private void btnCitaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitaModificarActionPerformed
        // TODO add your handling code here:
        int vIdCita = Integer.parseInt(txtCitaModificarIdCita.getText());
        int IndexLugar = cmbCitaModificarLugar.getSelectedIndex();
        String vLugar = (String)cmbCitaModificarLugar.getItemAt(IndexLugar);
        
        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.ModificarCitaLugar(vIdCita,vLugar));
    }//GEN-LAST:event_btnCitaModificarActionPerformed

    private void btnCitaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitaEliminarActionPerformed
        // TODO add your handling code here:
        int vIdCita = Integer.parseInt(txtCitaEliminarIdCita.getText());
        
        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.EliminarCita(vIdCita));
    }//GEN-LAST:event_btnCitaEliminarActionPerformed

    private void btnCitaMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitaMostrarActionPerformed
        // TODO add your handling code here:
        taCitaMostrar.setText(PantallaPrincipal.Gestora.MostrarCitas());
    }//GEN-LAST:event_btnCitaMostrarActionPerformed

    private void btnAbrirCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirCitasActionPerformed
        // TODO add your handling code here:
        int Resultado = Archivo.showOpenDialog(this);
        
        if (Resultado == (JFileChooser.CANCEL_OPTION)){
            return;
        }
        
        File ArchivoPorEnviar = Archivo.getSelectedFile();
        
        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.AbrirCitas(ArchivoPorEnviar));
    }//GEN-LAST:event_btnAbrirCitasActionPerformed

    private void btnGuardarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCitasActionPerformed
        // TODO add your handling code here:
        
        Archivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int resultado = Archivo.showSaveDialog(this);
        
        if (resultado == JFileChooser.CANCEL_OPTION){
            return;
        }
        
        File ArchivoPorGuardar = Archivo.getSelectedFile();
        
        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.guardarCitas(ArchivoPorGuardar));
        
    }//GEN-LAST:event_btnGuardarCitasActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirCitas;
    private javax.swing.JButton btnCitaAgregar;
    private javax.swing.JButton btnCitaBuscar;
    private javax.swing.JButton btnCitaEliminar;
    private javax.swing.JButton btnCitaModificar;
    private javax.swing.JButton btnCitaMostrar;
    private javax.swing.JButton btnGuardarCitas;
    private javax.swing.JComboBox cmbCitaAgregarLugar;
    private javax.swing.JComboBox cmbCitaModificarLugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAutobusModificarPlaca;
    private javax.swing.JLabel lblAutobusModificarPlaca1;
    private javax.swing.JLabel lblCitaAgregarCosto;
    private javax.swing.JLabel lblCitaAgregarLugar;
    private javax.swing.JLabel lblCitaAgregarVehiculoPlaca;
    private javax.swing.JLabel lblCitaBuscarIdCita;
    private javax.swing.JLabel lblCitaEliminarIdCita;
    private javax.swing.JTextArea taCitaBuscar;
    private javax.swing.JTextArea taCitaMostrar;
    private javax.swing.JTextField txtCitaAgregarCosto;
    private javax.swing.JTextField txtCitaAgregarVehiculoPlaca;
    private javax.swing.JTextField txtCitaBuscarIdCita;
    private javax.swing.JTextField txtCitaEliminarIdCita;
    private javax.swing.JTextField txtCitaModificarIdCita;
    // End of variables declaration//GEN-END:variables
}
