/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author laboratorio
 */
public class ModuloAutomovil extends javax.swing.JFrame {

    /**
     * Creates new form ModuloAutomovil
     */
    public ModuloAutomovil() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Módulo AutoMóviles");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblAutomovilAgregarMarca = new javax.swing.JLabel();
        lblAutomovilAgregarPlaca = new javax.swing.JLabel();
        lblAutomovilAgregarEstilo = new javax.swing.JLabel();
        lblAutomovilAgregarTransmision = new javax.swing.JLabel();
        txtAutomovilAgregarMarca = new javax.swing.JTextField();
        txtAutomovilAgregarPlaca = new javax.swing.JTextField();
        txtAutomovilAgregarTransmision = new javax.swing.JTextField();
        btnAutomovilAgregar = new javax.swing.JButton();
        cmbAutomovilAgregarEstilo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        lblAutomovilModificarPlaca = new javax.swing.JLabel();
        txtAutomovilModificarPlaca = new javax.swing.JTextField();
        btnAutomovilModificar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblAutomovilBuscarPlaca = new javax.swing.JLabel();
        txtAutomovilBuscarPlaca = new javax.swing.JTextField();
        btnAutomovilBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAutomovilBuscar = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        lblAutomovilEliminarPlaca = new javax.swing.JLabel();
        txtAutomovilEliminarPlaca = new javax.swing.JTextField();
        btnAutomovilEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblAutomovilAgregarMarca.setText("Marca:");

        lblAutomovilAgregarPlaca.setText("Placa:");

        lblAutomovilAgregarEstilo.setText("Estilo:");

        lblAutomovilAgregarTransmision.setText("Transmisión:");

        btnAutomovilAgregar.setText("Agregar");
        btnAutomovilAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomovilAgregarActionPerformed(evt);
            }
        });

        cmbAutomovilAgregarEstilo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sedan", "2 Puertas" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAutomovilAgregar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAutomovilAgregarMarca)
                                .addComponent(lblAutomovilAgregarPlaca)
                                .addComponent(lblAutomovilAgregarEstilo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAutomovilAgregarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAutomovilAgregarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbAutomovilAgregarEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lblAutomovilAgregarTransmision)
                            .addGap(18, 18, 18)
                            .addComponent(txtAutomovilAgregarTransmision, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutomovilAgregarMarca)
                    .addComponent(txtAutomovilAgregarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutomovilAgregarPlaca)
                    .addComponent(txtAutomovilAgregarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutomovilAgregarEstilo)
                    .addComponent(cmbAutomovilAgregarEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutomovilAgregarTransmision)
                    .addComponent(txtAutomovilAgregarTransmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAutomovilAgregar)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel2);

        lblAutomovilModificarPlaca.setText("Placa:");

        btnAutomovilModificar.setText("Modificar");
        btnAutomovilModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomovilModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblAutomovilModificarPlaca)
                        .addGap(27, 27, 27)
                        .addComponent(txtAutomovilModificarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAutomovilModificar))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutomovilModificarPlaca)
                    .addComponent(txtAutomovilModificarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAutomovilModificar)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar", jPanel3);

        lblAutomovilBuscarPlaca.setText("Placa:");

        btnAutomovilBuscar.setText("Buscar");
        btnAutomovilBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomovilBuscarActionPerformed(evt);
            }
        });

        taAutomovilBuscar.setEditable(false);
        taAutomovilBuscar.setColumns(20);
        taAutomovilBuscar.setRows(5);
        jScrollPane1.setViewportView(taAutomovilBuscar);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblAutomovilBuscarPlaca)
                        .addGap(27, 27, 27)
                        .addComponent(txtAutomovilBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAutomovilBuscar))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutomovilBuscarPlaca)
                    .addComponent(txtAutomovilBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAutomovilBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscar", jPanel4);

        lblAutomovilEliminarPlaca.setText("Placa:");

        btnAutomovilEliminar.setText("Eliminar");
        btnAutomovilEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomovilEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblAutomovilEliminarPlaca)
                        .addGap(27, 27, 27)
                        .addComponent(txtAutomovilEliminarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAutomovilEliminar))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutomovilEliminarPlaca)
                    .addComponent(txtAutomovilEliminarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAutomovilEliminar)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutomovilAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomovilAgregarActionPerformed
        // TODO add your handling code here:
        String vMarca = txtAutomovilAgregarMarca.getText();
        int vPlaca = Integer.parseInt(txtAutomovilAgregarPlaca.getText());

        int IndexEstilo = cmbAutomovilAgregarEstilo.getSelectedIndex();
        String vEstilo = (String)cmbAutomovilAgregarEstilo.getItemAt(IndexEstilo);
        String vTransmision = txtAutomovilAgregarTransmision.getText();

        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.AgregarAutomovil(vMarca, vPlaca, vEstilo, vTransmision));

    }//GEN-LAST:event_btnAutomovilAgregarActionPerformed

    private void btnAutomovilBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomovilBuscarActionPerformed
        // TODO add your handling code here:
        int vPlaca = Integer.parseInt(txtAutomovilBuscarPlaca.getText());
        
        taAutomovilBuscar.setText(PantallaPrincipal.Gestora.BuscarAutomovil(vPlaca));
    }//GEN-LAST:event_btnAutomovilBuscarActionPerformed

    private void btnAutomovilModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomovilModificarActionPerformed
        // TODO add your handling code here:
        int vPlaca = Integer.parseInt(txtAutomovilModificarPlaca.getText());
        String vMarca = JOptionPane.showInputDialog("Digite la nueva Marca");
        
        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.ModificarAutomovilMarca(vPlaca,vMarca));
    }//GEN-LAST:event_btnAutomovilModificarActionPerformed

    private void btnAutomovilEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomovilEliminarActionPerformed
        // TODO add your handling code here:
        int vPlaca = Integer.parseInt(txtAutomovilEliminarPlaca.getText());
        
        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.EliminarAutomovil(vPlaca));
    }//GEN-LAST:event_btnAutomovilEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutomovilAgregar;
    private javax.swing.JButton btnAutomovilBuscar;
    private javax.swing.JButton btnAutomovilEliminar;
    private javax.swing.JButton btnAutomovilModificar;
    private javax.swing.JComboBox cmbAutomovilAgregarEstilo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAutomovilAgregarEstilo;
    private javax.swing.JLabel lblAutomovilAgregarMarca;
    private javax.swing.JLabel lblAutomovilAgregarPlaca;
    private javax.swing.JLabel lblAutomovilAgregarTransmision;
    private javax.swing.JLabel lblAutomovilBuscarPlaca;
    private javax.swing.JLabel lblAutomovilEliminarPlaca;
    private javax.swing.JLabel lblAutomovilModificarPlaca;
    private javax.swing.JTextArea taAutomovilBuscar;
    private javax.swing.JTextField txtAutomovilAgregarMarca;
    private javax.swing.JTextField txtAutomovilAgregarPlaca;
    private javax.swing.JTextField txtAutomovilAgregarTransmision;
    private javax.swing.JTextField txtAutomovilBuscarPlaca;
    private javax.swing.JTextField txtAutomovilEliminarPlaca;
    private javax.swing.JTextField txtAutomovilModificarPlaca;
    // End of variables declaration//GEN-END:variables
}
