/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author laboratorio
 */
public class ModuloCamion extends javax.swing.JFrame {

    /**
     * Creates new form ModuloAutomovil
     */
    public ModuloCamion() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Módulo Camiones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblCamionAgregarMarca = new javax.swing.JLabel();
        lblCamionAgregarPlaca = new javax.swing.JLabel();
        lblCamionAgregarToneladas = new javax.swing.JLabel();
        lblCamionAgregarEjes = new javax.swing.JLabel();
        txtCamionAgregarMarca = new javax.swing.JTextField();
        txtCamionAgregarPlaca = new javax.swing.JTextField();
        txtCamionAgregarEjes = new javax.swing.JTextField();
        btnCamionAgregar = new javax.swing.JButton();
        txtCamionAgregarToneladas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblCamionModificarPlaca = new javax.swing.JLabel();
        txtCamionModificarPlaca = new javax.swing.JTextField();
        btnCamionModificar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblCamionBuscarPlaca = new javax.swing.JLabel();
        txtCamionBuscarPlaca = new javax.swing.JTextField();
        btnCamionBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taCamionBuscar = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        lblCamionEliminarPlaca = new javax.swing.JLabel();
        txtCamionEliminarPlaca = new javax.swing.JTextField();
        btnCamionEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblCamionAgregarMarca.setText("Marca:");

        lblCamionAgregarPlaca.setText("Placa:");

        lblCamionAgregarToneladas.setText("Toneladas:");

        lblCamionAgregarEjes.setText("Ejes:");

        btnCamionAgregar.setText("Agregar");
        btnCamionAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamionAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCamionAgregarEjes)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCamionAgregarMarca)
                            .addComponent(lblCamionAgregarPlaca)
                            .addComponent(lblCamionAgregarToneladas))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtCamionAgregarToneladas, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCamionAgregarEjes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCamionAgregarPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCamionAgregarMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCamionAgregar))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCamionAgregarMarca)
                    .addComponent(txtCamionAgregarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCamionAgregarPlaca)
                    .addComponent(txtCamionAgregarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCamionAgregarToneladas)
                    .addComponent(txtCamionAgregarToneladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCamionAgregarEjes)
                    .addComponent(txtCamionAgregarEjes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCamionAgregar)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel2);

        lblCamionModificarPlaca.setText("Placa:");

        btnCamionModificar.setText("Modificar");
        btnCamionModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamionModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCamionModificarPlaca)
                        .addGap(27, 27, 27)
                        .addComponent(txtCamionModificarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCamionModificar))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCamionModificarPlaca)
                    .addComponent(txtCamionModificarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCamionModificar)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar", jPanel3);

        lblCamionBuscarPlaca.setText("Placa:");

        btnCamionBuscar.setText("Buscar");
        btnCamionBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamionBuscarActionPerformed(evt);
            }
        });

        taCamionBuscar.setEditable(false);
        taCamionBuscar.setColumns(20);
        taCamionBuscar.setRows(5);
        jScrollPane1.setViewportView(taCamionBuscar);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblCamionBuscarPlaca)
                        .addGap(27, 27, 27)
                        .addComponent(txtCamionBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCamionBuscar))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCamionBuscarPlaca)
                    .addComponent(txtCamionBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCamionBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscar", jPanel4);

        lblCamionEliminarPlaca.setText("Placa:");

        btnCamionEliminar.setText("Eliminar");
        btnCamionEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamionEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblCamionEliminarPlaca)
                        .addGap(27, 27, 27)
                        .addComponent(txtCamionEliminarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCamionEliminar))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCamionEliminarPlaca)
                    .addComponent(txtCamionEliminarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCamionEliminar)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCamionAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamionAgregarActionPerformed
        // TODO add your handling code here:
        String vMarca = txtCamionAgregarMarca.getText();
        int vPlaca = Integer.parseInt(txtCamionAgregarPlaca.getText());
        int vToneladas = Integer.parseInt(txtCamionAgregarToneladas.getText());
        int vEjes = Integer.parseInt(txtCamionAgregarEjes.getText());

        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.AgregarCamion(vMarca, vPlaca, vToneladas, vEjes));

    }//GEN-LAST:event_btnCamionAgregarActionPerformed

    private void btnCamionBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamionBuscarActionPerformed
        // TODO add your handling code here:
        int vPlaca = Integer.parseInt(txtCamionBuscarPlaca.getText());
        
        taCamionBuscar.setText(PantallaPrincipal.Gestora.BuscarCamion(vPlaca));
    }//GEN-LAST:event_btnCamionBuscarActionPerformed

    private void btnCamionModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamionModificarActionPerformed
        // TODO add your handling code here:
        int vPlaca = Integer.parseInt(txtCamionModificarPlaca.getText());
        String vMarca = JOptionPane.showInputDialog("Digite la nueva Marca");
        
        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.ModificarCamionMarca(vPlaca,vMarca));
    }//GEN-LAST:event_btnCamionModificarActionPerformed

    private void btnCamionEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamionEliminarActionPerformed
        // TODO add your handling code here:
        int vPlaca = Integer.parseInt(txtCamionEliminarPlaca.getText());
        
        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.EliminarCamion(vPlaca));
    }//GEN-LAST:event_btnCamionEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCamionAgregar;
    private javax.swing.JButton btnCamionBuscar;
    private javax.swing.JButton btnCamionEliminar;
    private javax.swing.JButton btnCamionModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCamionAgregarEjes;
    private javax.swing.JLabel lblCamionAgregarMarca;
    private javax.swing.JLabel lblCamionAgregarPlaca;
    private javax.swing.JLabel lblCamionAgregarToneladas;
    private javax.swing.JLabel lblCamionBuscarPlaca;
    private javax.swing.JLabel lblCamionEliminarPlaca;
    private javax.swing.JLabel lblCamionModificarPlaca;
    private javax.swing.JTextArea taCamionBuscar;
    private javax.swing.JTextField txtCamionAgregarEjes;
    private javax.swing.JTextField txtCamionAgregarMarca;
    private javax.swing.JTextField txtCamionAgregarPlaca;
    private javax.swing.JTextField txtCamionAgregarToneladas;
    private javax.swing.JTextField txtCamionBuscarPlaca;
    private javax.swing.JTextField txtCamionEliminarPlaca;
    private javax.swing.JTextField txtCamionModificarPlaca;
    // End of variables declaration//GEN-END:variables
}
