/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author laboratorio
 */
public class ModuloAutobus extends javax.swing.JFrame {

    /**
     * Creates new form ModuloAutomovil
     */
    public ModuloAutobus() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Módulo Camiones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblAutobusAgregarMarca = new javax.swing.JLabel();
        lblAutobusAgregarPlaca = new javax.swing.JLabel();
        lblAutomovilAgregarEstilo = new javax.swing.JLabel();
        lblAutomovilAgregarTransmision = new javax.swing.JLabel();
        txtAutobusAgregarMarca = new javax.swing.JTextField();
        txtAutobusAgregarPlaca = new javax.swing.JTextField();
        txtAutobusAgregarModelo = new javax.swing.JTextField();
        btnAutobusAgregar = new javax.swing.JButton();
        txtAutobusAgregarCapacidad = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblAutobusModificarPlaca = new javax.swing.JLabel();
        txtAutobusModificarPlaca = new javax.swing.JTextField();
        btnAutobusModificar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblAutobusBuscarPlaca = new javax.swing.JLabel();
        txtAutobusBuscarPlaca = new javax.swing.JTextField();
        btnAutobusBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAutobusBuscar = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        lblAutobusEliminarPlaca = new javax.swing.JLabel();
        txtAutobusEliminarPlaca = new javax.swing.JTextField();
        btnAutobusEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblAutobusAgregarMarca.setText("Marca:");

        lblAutobusAgregarPlaca.setText("Placa:");

        lblAutomovilAgregarEstilo.setText("Capacidad:");

        lblAutomovilAgregarTransmision.setText("Modelo:");

        btnAutobusAgregar.setText("Agregar");
        btnAutobusAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutobusAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAutomovilAgregarTransmision)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutobusAgregarMarca)
                            .addComponent(lblAutobusAgregarPlaca)
                            .addComponent(lblAutomovilAgregarEstilo))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtAutobusAgregarCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAutobusAgregarModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutobusAgregarPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutobusAgregarMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAutobusAgregar))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutobusAgregarMarca)
                    .addComponent(txtAutobusAgregarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutobusAgregarPlaca)
                    .addComponent(txtAutobusAgregarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutomovilAgregarEstilo)
                    .addComponent(txtAutobusAgregarCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutomovilAgregarTransmision)
                    .addComponent(txtAutobusAgregarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAutobusAgregar)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel2);

        lblAutobusModificarPlaca.setText("Placa:");

        btnAutobusModificar.setText("Modificar");
        btnAutobusModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutobusModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblAutobusModificarPlaca)
                        .addGap(27, 27, 27)
                        .addComponent(txtAutobusModificarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAutobusModificar))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutobusModificarPlaca)
                    .addComponent(txtAutobusModificarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAutobusModificar)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar", jPanel3);

        lblAutobusBuscarPlaca.setText("Placa:");

        btnAutobusBuscar.setText("Buscar");
        btnAutobusBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutobusBuscarActionPerformed(evt);
            }
        });

        taAutobusBuscar.setEditable(false);
        taAutobusBuscar.setColumns(20);
        taAutobusBuscar.setRows(5);
        jScrollPane1.setViewportView(taAutobusBuscar);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblAutobusBuscarPlaca)
                        .addGap(27, 27, 27)
                        .addComponent(txtAutobusBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAutobusBuscar))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutobusBuscarPlaca)
                    .addComponent(txtAutobusBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAutobusBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscar", jPanel4);

        lblAutobusEliminarPlaca.setText("Placa:");

        btnAutobusEliminar.setText("Eliminar");
        btnAutobusEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutobusEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblAutobusEliminarPlaca)
                        .addGap(27, 27, 27)
                        .addComponent(txtAutobusEliminarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAutobusEliminar))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutobusEliminarPlaca)
                    .addComponent(txtAutobusEliminarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAutobusEliminar)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutobusAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutobusAgregarActionPerformed
        // TODO add your handling code here:
        String vMarca = txtAutobusAgregarMarca.getText();
        int vPlaca = Integer.parseInt(txtAutobusAgregarPlaca.getText());
        int vCapacidad = Integer.parseInt(txtAutobusAgregarCapacidad.getText());
        String vModelo = txtAutobusAgregarModelo.getText();

        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.AgregarAutobus(vMarca, vPlaca, vCapacidad, vModelo));

    }//GEN-LAST:event_btnAutobusAgregarActionPerformed

    private void btnAutobusBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutobusBuscarActionPerformed
        // TODO add your handling code here:
        int vPlaca = Integer.parseInt(txtAutobusBuscarPlaca.getText());
        
        taAutobusBuscar.setText(PantallaPrincipal.Gestora.BuscarAutobus(vPlaca));
    }//GEN-LAST:event_btnAutobusBuscarActionPerformed

    private void btnAutobusModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutobusModificarActionPerformed
        // TODO add your handling code here:
        int vPlaca = Integer.parseInt(txtAutobusModificarPlaca.getText());
        String vMarca = JOptionPane.showInputDialog("Digite la nueva Marca");
        
        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.ModificarAutobusMarca(vPlaca,vMarca));
    }//GEN-LAST:event_btnAutobusModificarActionPerformed

    private void btnAutobusEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutobusEliminarActionPerformed
        // TODO add your handling code here:
        int vPlaca = Integer.parseInt(txtAutobusEliminarPlaca.getText());
        
        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.EliminarAutobus(vPlaca));
    }//GEN-LAST:event_btnAutobusEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutobusAgregar;
    private javax.swing.JButton btnAutobusBuscar;
    private javax.swing.JButton btnAutobusEliminar;
    private javax.swing.JButton btnAutobusModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAutobusAgregarMarca;
    private javax.swing.JLabel lblAutobusAgregarPlaca;
    private javax.swing.JLabel lblAutobusBuscarPlaca;
    private javax.swing.JLabel lblAutobusEliminarPlaca;
    private javax.swing.JLabel lblAutobusModificarPlaca;
    private javax.swing.JLabel lblAutomovilAgregarEstilo;
    private javax.swing.JLabel lblAutomovilAgregarTransmision;
    private javax.swing.JTextArea taAutobusBuscar;
    private javax.swing.JTextField txtAutobusAgregarCapacidad;
    private javax.swing.JTextField txtAutobusAgregarMarca;
    private javax.swing.JTextField txtAutobusAgregarModelo;
    private javax.swing.JTextField txtAutobusAgregarPlaca;
    private javax.swing.JTextField txtAutobusBuscarPlaca;
    private javax.swing.JTextField txtAutobusEliminarPlaca;
    private javax.swing.JTextField txtAutobusModificarPlaca;
    // End of variables declaration//GEN-END:variables
}
