/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author laboratorio
 */
public class ModuloMotocicleta extends javax.swing.JFrame {

    /**
     * Creates new form ModuloAutomovil
     */
    public ModuloMotocicleta() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Módulo MotoCicleta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblMotocicletaAgregarMarca = new javax.swing.JLabel();
        lblAutomovilAgregarPlaca = new javax.swing.JLabel();
        lbMotocicletaAgregarCilindraje = new javax.swing.JLabel();
        lblMotocicletaAgregarColor = new javax.swing.JLabel();
        txtMotocicletaAgregarMarca = new javax.swing.JTextField();
        txtMotocicletaAgregarCilindraje = new javax.swing.JTextField();
        txtMotocicletaAgregarColor = new javax.swing.JTextField();
        btnMotocicletaAgregar = new javax.swing.JButton();
        txtMotocicletaAgregarPlaca = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblMotocicletaModificarPlaca = new javax.swing.JLabel();
        txtMotocicletaModificarPlaca = new javax.swing.JTextField();
        btnMotocicletaModificar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblMotocicletaBuscarPlaca = new javax.swing.JLabel();
        txtMotocicletaBuscarPlaca = new javax.swing.JTextField();
        btnMotocicletaBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMotocicletaBuscar = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        lblMotocicletaEliminarPlaca = new javax.swing.JLabel();
        txtMotocicletaEliminarPlaca = new javax.swing.JTextField();
        btnMotocicletaEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblMotocicletaAgregarMarca.setText("Marca:");

        lblAutomovilAgregarPlaca.setText("Placa:");

        lbMotocicletaAgregarCilindraje.setText("Cilindraje:");

        lblMotocicletaAgregarColor.setText("Color:");

        btnMotocicletaAgregar.setText("Agregar");
        btnMotocicletaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotocicletaAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMotocicletaAgregarMarca)
                            .addComponent(lblAutomovilAgregarPlaca)
                            .addComponent(lbMotocicletaAgregarCilindraje)
                            .addComponent(lblMotocicletaAgregarColor))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMotocicletaAgregarColor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMotocicletaAgregarCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMotocicletaAgregarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMotocicletaAgregarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnMotocicletaAgregar)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMotocicletaAgregarMarca)
                    .addComponent(txtMotocicletaAgregarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutomovilAgregarPlaca)
                    .addComponent(txtMotocicletaAgregarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMotocicletaAgregarCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMotocicletaAgregarCilindraje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMotocicletaAgregarColor)
                    .addComponent(txtMotocicletaAgregarColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMotocicletaAgregar)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel2);

        lblMotocicletaModificarPlaca.setText("Placa:");

        btnMotocicletaModificar.setText("Modificar");
        btnMotocicletaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotocicletaModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblMotocicletaModificarPlaca)
                        .addGap(27, 27, 27)
                        .addComponent(txtMotocicletaModificarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMotocicletaModificar))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMotocicletaModificarPlaca)
                    .addComponent(txtMotocicletaModificarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMotocicletaModificar)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar", jPanel3);

        lblMotocicletaBuscarPlaca.setText("Placa:");

        txtMotocicletaBuscarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotocicletaBuscarPlacaActionPerformed(evt);
            }
        });

        btnMotocicletaBuscar.setText("Buscar");
        btnMotocicletaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotocicletaBuscarActionPerformed(evt);
            }
        });

        taMotocicletaBuscar.setEditable(false);
        taMotocicletaBuscar.setColumns(20);
        taMotocicletaBuscar.setRows(5);
        jScrollPane1.setViewportView(taMotocicletaBuscar);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblMotocicletaBuscarPlaca)
                        .addGap(27, 27, 27)
                        .addComponent(txtMotocicletaBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMotocicletaBuscar))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMotocicletaBuscarPlaca)
                    .addComponent(txtMotocicletaBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMotocicletaBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscar", jPanel4);

        lblMotocicletaEliminarPlaca.setText("Placa:");

        btnMotocicletaEliminar.setText("Eliminar");
        btnMotocicletaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotocicletaEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblMotocicletaEliminarPlaca)
                        .addGap(27, 27, 27)
                        .addComponent(txtMotocicletaEliminarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMotocicletaEliminar))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMotocicletaEliminarPlaca)
                    .addComponent(txtMotocicletaEliminarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMotocicletaEliminar)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMotocicletaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotocicletaAgregarActionPerformed
        // TODO add your handling code here:
        String vMarca = txtMotocicletaAgregarMarca.getText();
        int vPlaca = Integer.parseInt(txtMotocicletaAgregarPlaca.getText());
        double vCilindraje = Double.parseDouble(txtMotocicletaAgregarCilindraje.getText());
        String vColor = txtMotocicletaAgregarColor.getText();

        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.AgregarMotocicleta(vMarca, vPlaca, vCilindraje, vColor));

    }//GEN-LAST:event_btnMotocicletaAgregarActionPerformed

    private void btnMotocicletaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotocicletaBuscarActionPerformed
        // TODO add your handling code here:
        int vPlaca = Integer.parseInt(txtMotocicletaBuscarPlaca.getText());
        
        taMotocicletaBuscar.setText(PantallaPrincipal.Gestora.BuscarMotocicleta(vPlaca));
    }//GEN-LAST:event_btnMotocicletaBuscarActionPerformed

    private void btnMotocicletaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotocicletaModificarActionPerformed
        // TODO add your handling code here:
        int vPlaca = Integer.parseInt(txtMotocicletaModificarPlaca.getText());
        String vMarca = JOptionPane.showInputDialog("Digite la nueva Marca");
        
        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.ModificarMotocicletaMarca(vPlaca,vMarca));
    }//GEN-LAST:event_btnMotocicletaModificarActionPerformed

    private void btnMotocicletaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotocicletaEliminarActionPerformed
        // TODO add your handling code here:
        int vPlaca = Integer.parseInt(txtMotocicletaEliminarPlaca.getText());
        
        JOptionPane.showMessageDialog(null, PantallaPrincipal.Gestora.EliminarMotocicleta(vPlaca));
    }//GEN-LAST:event_btnMotocicletaEliminarActionPerformed

    private void txtMotocicletaBuscarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotocicletaBuscarPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotocicletaBuscarPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMotocicletaAgregar;
    private javax.swing.JButton btnMotocicletaBuscar;
    private javax.swing.JButton btnMotocicletaEliminar;
    private javax.swing.JButton btnMotocicletaModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbMotocicletaAgregarCilindraje;
    private javax.swing.JLabel lblAutomovilAgregarPlaca;
    private javax.swing.JLabel lblMotocicletaAgregarColor;
    private javax.swing.JLabel lblMotocicletaAgregarMarca;
    private javax.swing.JLabel lblMotocicletaBuscarPlaca;
    private javax.swing.JLabel lblMotocicletaEliminarPlaca;
    private javax.swing.JLabel lblMotocicletaModificarPlaca;
    private javax.swing.JTextArea taMotocicletaBuscar;
    private javax.swing.JTextField txtMotocicletaAgregarCilindraje;
    private javax.swing.JTextField txtMotocicletaAgregarColor;
    private javax.swing.JTextField txtMotocicletaAgregarMarca;
    private javax.swing.JTextField txtMotocicletaAgregarPlaca;
    private javax.swing.JTextField txtMotocicletaBuscarPlaca;
    private javax.swing.JTextField txtMotocicletaEliminarPlaca;
    private javax.swing.JTextField txtMotocicletaModificarPlaca;
    // End of variables declaration//GEN-END:variables
}
